Buggy-api-assignment
webonise/buggy-api pull request #24
Opened 2019-12-23 06:27 UTC by sahadevbite

changes added for login from both user and not to save duplicate record.

2019-12-23 06:36 UTC, parikshitd-webonise requested changes
The code doesn't restrict a user from inserting duplicates records. The issue still persists on a database lavel.

2019-12-23 06:36 UTC, parikshitd-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
> +    		return null;
Bad practice to return null.

2019-12-23 06:37 UTC, parikshitd-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
> +    	System.err.println(check);
We should log instead of `println`.

2019-12-23 06:38 UTC, parikshitd-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
> +    	System.err.println(check);
We should we log.

2019-12-30 07:12 UTC, sudharani-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
> +	static Log logger = LogFactory.getLog(SignUpController.class);
why not private ?

2019-12-30 07:13 UTC, sudharani-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
>  @RequestMapping("/")
what is the difference between @RestController, @RequestMapping what if I want to use only one Annotation

2019-12-30 07:14 UTC, sudharani-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
> +    	int check = userService.checkUser(userRequest.getLoginId());
include exception handling?

2019-12-30 07:15 UTC, sudharani-webonise commented on src/main/java/com/webonise/login/controller/SignUpController.java
> +    	if(check>0) {
avoid magic number checks

2021-02-04 13:08 UTC, closed without merging