Resolved duplicate entries in db
webonise/buggy-api pull request #4
Opened 2019-09-12 11:30 UTC by amolyeole

Root cause:            
           - Duplicate entries for user1 in db

    Solution:
            - Add migration to remove duplicate entries for user1 and add
            only one entry again.

    Enhancement:
            - Login id field should be unique to block duplicate entries for
            email ids

2019-09-12 12:40 UTC, parikshitd-webonise requested changes
Can please make changes from code side as well and I am able to see `Login id field should be unique to block duplicate entries for email ids` so it will be good if you add the same.

2019-09-12 13:14 UTC, amolyeole commented
yes I can do this by using unique key constrain

2019-09-12 15:14 UTC, amolyeole commented
Please check it's and let me know

Thanks & Regards.
Mr. Amol Yeole
Mobile No.: 9970630438

On Thu 12 Sep, 2019, 6:32 PM Amol Yeole, <amolyeole88@gmail.com> wrote:

>  I can also unique constraint apply for this
>
> Thanks & Regards.
> Mr. Amol Yeole
> Mobile No.: 9970630438
>
> On Thu 12 Sep, 2019, 6:10 PM Parikshit Deshpande, <
> notifications@github.com> wrote:
>
>> *@parikshitd-webonise* requested changes on this pull request.
>>
>> Can please make changes from code side as well and I am able to see Login
>> id field should be unique to block duplicate entries for email ids
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/webonise/buggy-api/pull/4?email_source=notifications&email_token=AJG4Z6BIXEG5ZJ5GRGJDNTLQJI2ETA5CNFSM4IWCTWO2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCEQVLVY#pullrequestreview-287397335>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AJG4Z6HNS67W4R3FAMDZ4WLQJI2ETANCNFSM4IWCTWOQ>
>> .
>>
>

2019-09-13 06:19 UTC, parikshitd-webonise approved these changes

2019-09-13 07:09 UTC, closed without merging